### ISSUE TITLE
react-scripts not installed and yarn doesn't start because of it

### ISSUE THREAD

**Issue by johnrraymond** [GtLibrary/thegreatlibrary#23]
D:\thegreatlibrary\react-frontend>yarn start
yarn run v1.22.10
$ react-scripts start
'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

D:\thegreatlibrary\react-frontend>

**Comment by Ken-tech-max** [comment]
Please use the command `npm i -g react-scripts`.

**Comment by Ken-tech-max** [comment]
it seems like you can `yarn` and `yarn start`.
That may work.

**Comment by johnrraymond** [comment]
The issue was not running: yarn && yarn start
