### ISSUE TITLE
Update readme file for New github project

### ISSUE THREAD

**Issue by alzmob** [GtLibrary/thegreatlibrary#42]
current readme is for the old version.
so I suggest to readme file update.
main update part that I suggest is below:
--git clone https://github.com/johnrraymond/greatlibraryserver
// this part is for the old version
in current version, we have need to fix the source code for frontend update in current user login and fix the backend source code in john user login.
this is very inconvenience.
so I am suggest to this part update to below:
--git clone https://github.com/GtLibrary/thegreatlibrary.git
so after this part update, source code fix is very convenience in one user login.
I hope to hear opinion in team members.

**Comment by subsilico** [comment]
I believe they are both out of date

**Comment by johnrraymond** [comment]
I'll merge them?

**Comment by alzmob** [comment]
yes, but if you agree, I will do it.

**Comment by johnrraymond** [comment]
Go ahead and do it please, alzmod.

**Comment by alzmob** [comment]
I have already pushed it
